from datetime import timezone
from datetime import timedelta

utc_offsets_int = {
    'canada': -5,  # capital: ottawa (utc-5)
    'congo (democratic republic of the congo)': 0,  # capital: kinshasa (utc+0)
    'indonesia': +7,  # capital: jakarta (utc+7)
    'kazakhstan': +6,  # capital: nur-sultan (utc+6)
    'mexico': -6,  # capital: mexico city (utc-6)
    'mongolia': +8,  # capital: ulaanbaatar (utc+8)
    'russia': +3,  # capital: moscow (utc+3)
    'ukraine': +2,  # capital: kyiv (utc+2)
    'usa': -5,  # capital: washington, d.c. (utc-5)
    'new zealand': +13,  # capital: wellington (utc+13)
    'afghanistan': +4,
    'albania': +1,
    'algeria': +1,
    'andorra': +1,
    'angola': +1,
    'antigua and barbuda': -4,
    'argentina': -3,
    'armenia': +4,
    'australia': +10,
    'austria': +1,
    'azerbaijan': +4,
    'bahamas': -5,
    'bahrain': +3,
    'bangladesh': +6,
    'barbados': -4,
    'belarus': +3,
    'belgium': +1,
    'belize': -6,
    'benin': +1,
    'bhutan': +6,
    'bolivia': -4,
    'bosnia and herzegovina': +1,
    'botswana': +2,
    'brazil': -3,
    'brunei': +8,
    'bulgaria': +2,
    'burkina faso': 0,
    'burundi': +2,
    'cabo verde': -1,
    'cambodia': +7,
    'cameroon': +1,
    'central african republic': +1,
    'chad': +1,
    'chile': -3,
    'china': +8,
    'colombia': -5,
    'comoros': +3,
    'congo (congo-brazzaville)': +1,
    'costa rica': -6,
    'croatia': +1,
    'cuba': -5,
    'cyprus': +2,
    'czech republic': +1,
    'denmark': +1,
    'djibouti': +3,
    'dominica': -4,
    'dominican republic': -4,
    'ecuador': -5,
    'egypt': +2,
    'el salvador': -6,
    'equatorial guinea': +1,
    'eritrea': +3,
    'estonia': +2,
    'eswatini': +2,
    'ethiopia': +3,
    'fiji': +12,
    'finland': +2,
    'france': +1,
    'gabon': +1,
    'gambia': 0,
    'georgia': +4,
    'germany': +1,
    'ghana': 0,
    'greece': +2,
    'grenada': -4,
    'guatemala': -6,
    'guinea': 0,
    'guinea-bissau': 0,
    'guyana': -4,
    'haiti': -5,
    'honduras': -6,
    'hungary': +1,
    'iceland': 0,
    'india': +5.5,
    'iran': +3.5,
    'iraq': +3,
    'ireland': 0,
    'israel': +2,
    'italy': +1,
    'jamaica': -5,
    'japan': +9,
    'jordan': +2,
    'kenya': +3,
    'kiribati': +12,
    'kuwait': +3,
    'kyrgyzstan': +6,
    'laos': +7,
    'latvia': +2,
    'lebanon': +2,
    'lesotho': +2,
    'liberia': 0,
    'libya': +2,
    'liechtenstein': +1,
    'lithuania': +2,
    'luxembourg': +1,
    'madagascar': +3,
    'malawi': +2,
    'malaysia': +8,
    'maldives': +5,
    'mali': 0,
    'malta': +1,
    'marshall islands': +12,
    'mauritania': 0,
    'mauritius': +4,
    'moldova': +2,
    'monaco': +1,
    'montenegro': +1,
    'morocco': +1,
    'mozambique': +2,
    'myanmar (burma)': +6.5,
    'namibia': +2,
    'nauru': +12,
    'nepal': +5.75,
    'netherlands': +1,
    'nicaragua': -6,
    'niger': +1,
    'nigeria': +1,
    'north korea': +9,
    'north macedonia': +1,
    'norway': +1,
    'oman': +4,
    'pakistan': +5,
    'palau': +9,
    'panama': -5,
    'papua new guinea': +10,
    'paraguay': -4,
    'peru': -5,
    'philippines': +8,
    'poland': +1,
    'portugal': +0,
    'qatar': +3,
    'romania': +2,
    'rwanda': +2,
    'saint kitts and nevis': -4,
    'saint lucia': -4,
    'saint vincent and the grenadines': -4,
    'samoa': +13,
    'san marino': +1,
    'sao tome and principe': 0,
    'saudi arabia': +3,
    'senegal': 0,
    'serbia': +1,
    'seychelles': +4,
    'sierra leone': 0,
    'singapore': +8,
    'slovakia': +1,
    'slovenia': +1,
    'solomon islands': +11,
    'somalia': +3,
    'south africa': +2,
    'south korea': +9,
    'south sudan': +3,
    'spain': +1,
    'sri lanka': +5.5,
    'sudan': +2,
    'suriname': -3,
    'sweden': +1,
    'switzerland': +1,
    'syria': +2,
    'taiwan': +8,
    'tajikistan': +5,
    'tanzania': +3,
    'thailand': +7,
    'timor-leste': +9,
    'togo': 0,
    'tonga': +13,
    'trinidad and tobago': -4,
    'tunisia': +1,
    'turkey': +3,
    'turkmenistan': +5,
    'tuvalu': +12,
    'uganda': +3,
    'united arab emirates': +4,
    'united kingdom': 0,
    'uruguay': -3,
    'uzbekistan': +5,
    'vanuatu': +11,
    'vatican city': +1,
    'venezuela': -4,
    'vietnam': +7,
    'yemen': +3,
    'zambia': +2,
    'zimbabwe': +2,
}

utc_offsets = {}

for country, offset in utc_offsets_int.items():
    utc_offsets[country] = timezone(timedelta(hours=offset))

print('Log: UTC offsets generated!')

# country_datetime = datetime.now(utc_offsets['belarus'])
# datetime_str = datetime.strftime(country_datetime, '%d-%m-%Y %H:%M')
# print('Belarus: ', datetime_str)
